services:
  backend:
    container_name: fastapi_auth_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn server.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=mysql://fastapi_user:fastapi_password@mysql:3306/fastapi_auth
    volumes:
      - .:/app
    depends_on: 
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fastapi_auth
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  test_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fastapi_auth
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
    ports:
      - "3307:3306"
    volumes:
      - test_mysql_data:/var/lib/test_mysql


volumes:
  mysql_data:
  test_mysql_data: